(*                                                                            *)
(* File generated by the B&R AS 4 control config generator                    *)
(*                                                                            *)
(*     Provider: machineering                                                 *)
(*  Application: industrialPhysics_2.4.master                                 *)
(* Architecture: Windows 64 Bit                                               *)
(*      Version: 2.4.11457.master                                             *)
(*        Build: 095f6f04a                                                    *)
(*         Date: 2020-10-12, Time: 08:55:42                                   *)
(*                                                                            *)

TYPE
Saw_INPUTS_32BIT : STRUCT



		NumSignals	: INT := 4;

        diDriveParallelAtFront : BOOL := 0;
        (* BOOL diDriveParallelAtFront *)
        diDriveParallelAtBack : BOOL := 0;
        (* BOOL diDriveParallelAtBack *)
        diDriveCutAtFront : BOOL := 0;
        (* BOOL diDriveCutAtFront *)
        diDriveCutAtBack : BOOL := 0;
        (* BOOL diDriveCutAtBack *)

	END_STRUCT;

Saw_OUTPUTS_32BIT : STRUCT


		NumSignals	: INT := 4;

        doSawOn : BOOL := 0;
        (* BOOL doSawOn *)
        aoTreeVelocity : REAL ;
        (* LREAL aoTreeVelocity *)
        aoDriveParallelPosition : REAL ;
        (* LREAL aoDriveParallelPosition *)
        aoDriveCutPosition : REAL ;
        (* LREAL aoDriveCutPosition *)

	END_STRUCT;


END_TYPE
